version: '3'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app:delegated
      - ~/.composer:/home/root/.composer:delegated
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: smiut
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
        - "3307:3306"
